version: '3'
services:
  anemos-api:
    container_name: anemos-api
    build:
      context: .
      dockerfile: ./build/api/Dockerfile
    volumes:
      - ./:/workspace/
    restart: always
    ports:
      - 5000:80
    env_file:
      - .env

  anemos-exe-realtime:
    container_name: anemos-exe-realtime
    build:
      context: .
      dockerfile: ./build/autoexe/Dockerfile
    command: [ 'python', 'autoexe/realtime.py' ]
    environment:
      TZ: 'Asia/Tokyo'
      ANALYZE: 'http://anemos-analyze'
    restart: always

    volumes:
      - ./:/workspace/
    env_file:
      - .env

  anemos-exe-timer:
    container_name: anemos-exe-timer
    build:
      context: .
      dockerfile: ./build/autoexe/Dockerfile
    command: [ 'python', 'autoexe/timer.py' ]
    restart: always
    volumes:
      - ./:/workspace/
    env_file:
      - .env

  anemos-commander:
    container_name: anemos-commander
    build:
      context: .
      dockerfile: ./build/main/Dockerfile
    environment:
      BSKY_USER: 'siestabot.bsky.social'
      BSKY_PASS: 'dNJ2U23EU2Wr-ny'
      ALERT_URL: 'https://discord.com/api/webhooks/1204746660228366376/EcsaNqpivJTIpYLYqtqlW1vI0p_aESbNMLkBc3vx1Af0xBC5ZFeQBHg_K_msRom3473L'
      LINE_TOKEN: 'kratnWiCO8dw49BW9jTtmyGPFVLJp9tQOW+Gm39dOPhFgzdnb3WqbRivINcTs0k61su5GF2hS4ZHSU35YC8G4/XQyCQtovygzJ1UcWa2VIBEqpwdYzj9ybd6YG1FuMgSWrviWqjuJdLvZvyCXSAZPAdB04t89/1O/w1cDnyilFU='
      STAGE: 'DEVELOP'
    volumes:
      - ./:/src/
    ports:
      - 13080:80
    depends_on:
      - anemos-maria-database
      - anemos-mongo-database
      - anemos-redis-database
    restart: always
    env_file:
      - .env

  anemos-maria-database:
    container_name: anemos-maria-database
    image: mariadb
    expose:
      - 3306
    volumes:
      - ./db/maria:/var/lib/mysql
    restart: always
    env_file:
      - .env

  anemos-mongo-database:
    container_name: anemos-mongo-database
    image: mongo
    restart: always
    volumes:
      - ./db/mongo:/data/db
    ports:
      - 27171:27017
    env_file:
      - .env

  anemos-redis-database:
    container_name: anemos-redis-database
    image: redis:latest
    restart: always
    expose:
      - 6379
    volumes:
      - "./db/redis:/data"
    env_file:
      - .env
