apiVersion: v1
kind: Namespace
metadata:
  name: anemos-public

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: anemos-public-scaler
  namespace: anemos-public
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: anemos-public-api-replica-set 
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: anemos-public
  name: anemos-public-api-replica-set
  labels:
    app: anemos-public-api
spec:
  replicas: 2  # 2つのレプリカ
  selector:
    matchLabels:
      app: anemos-public-api
  template:
    metadata:
      labels:
        app: anemos-public-api
    spec:
      containers:
      - name: anemos-public-api
        image: solufit.azurecr.io/anemos-public-api
        ports:
        - containerPort: 8080
        env:
        - name: SYSTEM
          value: DEVELOP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: anemos-public
  name: anemos-public-api-collector
spec:
  replicas: 1  # デプロイメントのレプリカ数は1に設定
  selector:
    matchLabels:
      app: anemos-public-api-collector
  template:
    metadata:
      labels:
        app: anemos-public-api-collector
    spec:
      containers:
      - name: anemos-public-api-collector
        image: solufit.azurecr.io/anemos-public-api-collector
        env:
        - name: SYSTEM
          value: DEVELOP
---
apiVersion: v1
kind: Service
metadata:
  namespace: anemos-public
  name: my-app-service
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

